# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edytor2.ui'
#
# Created: Thu Dec 26 20:48:59 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_notepad(object):
    def setupUi(self, notepad):
        notepad.setObjectName(_fromUtf8("notepad"))
        notepad.resize(475, 592)
        self.tabWidget = QtGui.QTabWidget(notepad)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 451, 541))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Enrollment = QtGui.QWidget()
        self.Enrollment.setObjectName(_fromUtf8("Enrollment"))
        self.groupBox = QtGui.QGroupBox(self.Enrollment)
        self.groupBox.setGeometry(QtCore.QRect(20, 0, 401, 201))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(150, 40, 241, 121))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.Username = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.Username.setPlaceholderText(_fromUtf8(""))
        self.Username.setObjectName(_fromUtf8("Username"))
        self.horizontalLayout_2.addWidget(self.Username)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.Userage = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.Userage.setMaximum(100)
        self.Userage.setProperty("value", 20)
        self.Userage.setObjectName(_fromUtf8("Userage"))
        self.horizontalLayout_3.addWidget(self.Userage)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.Usersex = QtGui.QComboBox(self.verticalLayoutWidget)
        self.Usersex.setObjectName(_fromUtf8("Usersex"))
        self.Usersex.addItem(_fromUtf8(""))
        self.Usersex.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.Usersex)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 131, 151))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.Userimage = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Userimage.sizePolicy().hasHeightForWidth())
        self.Userimage.setSizePolicy(sizePolicy)
        self.Userimage.setText(_fromUtf8(""))
        self.Userimage.setObjectName(_fromUtf8("Userimage"))
        self.verticalLayout_2.addWidget(self.Userimage)
        self.UploadImage = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.UploadImage.setObjectName(_fromUtf8("UploadImage"))
        self.verticalLayout_2.addWidget(self.UploadImage)
        self.Userchooser = QtGui.QComboBox(self.groupBox)
        self.Userchooser.setGeometry(QtCore.QRect(220, 10, 171, 29))
        self.Userchooser.setObjectName(_fromUtf8("Userchooser"))
        self.Userchooser.addItem(_fromUtf8(""))
        self.UpdateInfo = QtGui.QPushButton(self.groupBox)
        self.UpdateInfo.setGeometry(QtCore.QRect(280, 160, 111, 31))
        self.UpdateInfo.setObjectName(_fromUtf8("UpdateInfo"))
        self.ClearInfo = QtGui.QPushButton(self.groupBox)
        self.ClearInfo.setGeometry(QtCore.QRect(160, 160, 111, 31))
        self.ClearInfo.setObjectName(_fromUtf8("ClearInfo"))
        self.groupBox_2 = QtGui.QGroupBox(self.Enrollment)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 200, 421, 291))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.Textreading = QtGui.QTextBrowser(self.groupBox_2)
        self.Textreading.setGeometry(QtCore.QRect(0, 60, 411, 101))
        self.Textreading.setObjectName(_fromUtf8("Textreading"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(0, 30, 431, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.Animation = QtGui.QLabel(self.groupBox_2)
        self.Animation.setGeometry(QtCore.QRect(0, 160, 61, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Animation.sizePolicy().hasHeightForWidth())
        self.Animation.setSizePolicy(sizePolicy)
        self.Animation.setText(_fromUtf8(""))
        self.Animation.setObjectName(_fromUtf8("Animation"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 230, 411, 61))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.enroll = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.enroll.setObjectName(_fromUtf8("enroll"))
        self.horizontalLayout.addWidget(self.enroll)
        self.startTrain = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.startTrain.setObjectName(_fromUtf8("startTrain"))
        self.horizontalLayout.addWidget(self.startTrain)
        self.dumpBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.dumpBtn.setObjectName(_fromUtf8("dumpBtn"))
        self.horizontalLayout.addWidget(self.dumpBtn)
        self.loadBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.loadBtn.setObjectName(_fromUtf8("loadBtn"))
        self.horizontalLayout.addWidget(self.loadBtn)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(140, 180, 221, 41))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.enrollRecord = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.enrollRecord.setObjectName(_fromUtf8("enrollRecord"))
        self.horizontalLayout_5.addWidget(self.enrollRecord)
        self.stopEnrollRecord = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.stopEnrollRecord.setObjectName(_fromUtf8("stopEnrollRecord"))
        self.horizontalLayout_5.addWidget(self.stopEnrollRecord)
        self.enrollTime = QtGui.QLabel(self.groupBox_2)
        self.enrollTime.setGeometry(QtCore.QRect(73, 190, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.enrollTime.setFont(font)
        self.enrollTime.setObjectName(_fromUtf8("enrollTime"))
        self.enrollFile = QtGui.QToolButton(self.groupBox_2)
        self.enrollFile.setGeometry(QtCore.QRect(370, 185, 31, 29))
        self.enrollFile.setObjectName(_fromUtf8("enrollFile"))
        self.tabWidget.addTab(self.Enrollment, _fromUtf8(""))
        self.Recognition = QtGui.QWidget()
        self.Recognition.setObjectName(_fromUtf8("Recognition"))
        self.groupBox_3 = QtGui.QGroupBox(self.Recognition)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 0, 561, 341))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(140, 30, 271, 41))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.Reco_Verificationcheckbox = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Reco_Verificationcheckbox.setFont(font)
        self.Reco_Verificationcheckbox.setIconSize(QtCore.QSize(24, 24))
        self.Reco_Verificationcheckbox.setTristate(False)
        self.Reco_Verificationcheckbox.setObjectName(_fromUtf8("Reco_Verificationcheckbox"))
        self.horizontalLayout_6.addWidget(self.Reco_Verificationcheckbox)
        self.Reco_Verification = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.Reco_Verification.setEnabled(False)
        self.Reco_Verification.setObjectName(_fromUtf8("Reco_Verification"))
        self.horizontalLayout_6.addWidget(self.Reco_Verification)
        self.Animation_2 = QtGui.QLabel(self.groupBox_3)
        self.Animation_2.setGeometry(QtCore.QRect(30, 70, 61, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Animation_2.sizePolicy().hasHeightForWidth())
        self.Animation_2.setSizePolicy(sizePolicy)
        self.Animation_2.setText(_fromUtf8(""))
        self.Animation_2.setObjectName(_fromUtf8("Animation_2"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(260, 180, 131, 161))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.Reco_Userimage = QtGui.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Reco_Userimage.sizePolicy().hasHeightForWidth())
        self.Reco_Userimage.setSizePolicy(sizePolicy)
        self.Reco_Userimage.setText(_fromUtf8(""))
        self.Reco_Userimage.setObjectName(_fromUtf8("Reco_Userimage"))
        self.verticalLayout_3.addWidget(self.Reco_Userimage)
        self.recoUsername = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.recoUsername.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recoUsername.sizePolicy().hasHeightForWidth())
        self.recoUsername.setSizePolicy(sizePolicy)
        self.recoUsername.setAlignment(QtCore.Qt.AlignCenter)
        self.recoUsername.setReadOnly(True)
        self.recoUsername.setObjectName(_fromUtf8("recoUsername"))
        self.verticalLayout_3.addWidget(self.recoUsername)
        self.recoTime = QtGui.QLabel(self.groupBox_3)
        self.recoTime.setGeometry(QtCore.QRect(120, 100, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.recoTime.setFont(font)
        self.recoTime.setObjectName(_fromUtf8("recoTime"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(210, 62, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 180, 231, 151))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.newReco = QtGui.QPushButton(self.groupBox_3)
        self.newReco.setGeometry(QtCore.QRect(10, 35, 101, 31))
        self.newReco.setObjectName(_fromUtf8("newReco"))
        self.recoProgressBar = QtGui.QProgressBar(self.groupBox_3)
        self.recoProgressBar.setGeometry(QtCore.QRect(10, 140, 401, 23))
        self.recoProgressBar.setProperty("value", 0)
        self.recoProgressBar.setObjectName(_fromUtf8("recoProgressBar"))
        self.horizontalLayoutWidget_6 = QtGui.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(182, 90, 191, 41))
        self.horizontalLayoutWidget_6.setObjectName(_fromUtf8("horizontalLayoutWidget_6"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.recoRecord = QtGui.QPushButton(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.recoRecord.setFont(font)
        self.recoRecord.setObjectName(_fromUtf8("recoRecord"))
        self.horizontalLayout_9.addWidget(self.recoRecord)
        self.stopRecoRecord = QtGui.QPushButton(self.horizontalLayoutWidget_6)
        self.stopRecoRecord.setObjectName(_fromUtf8("stopRecoRecord"))
        self.horizontalLayout_9.addWidget(self.stopRecoRecord)
        self.recoFile = QtGui.QToolButton(self.groupBox_3)
        self.recoFile.setGeometry(QtCore.QRect(380, 95, 29, 29))
        self.recoFile.setObjectName(_fromUtf8("recoFile"))
        self.groupBox_6 = QtGui.QGroupBox(self.Recognition)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 330, 411, 171))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.groupBox_6)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 401, 41))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_8 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_7.addWidget(self.label_8)
        self.Reco_Inputfile = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        self.Reco_Inputfile.setObjectName(_fromUtf8("Reco_Inputfile"))
        self.horizontalLayout_7.addWidget(self.Reco_Inputfile)
        self.Reco_Inputchooser = QtGui.QToolButton(self.horizontalLayoutWidget_4)
        self.Reco_Inputchooser.setObjectName(_fromUtf8("Reco_Inputchooser"))
        self.horizontalLayout_7.addWidget(self.Reco_Inputchooser)
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.groupBox_6)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 80, 401, 41))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_9 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.Reco_Outputfile = QtGui.QLineEdit(self.horizontalLayoutWidget_5)
        self.Reco_Outputfile.setObjectName(_fromUtf8("Reco_Outputfile"))
        self.horizontalLayout_8.addWidget(self.Reco_Outputfile)
        self.Reco_Outputchooser = QtGui.QToolButton(self.horizontalLayoutWidget_5)
        self.Reco_Outputchooser.setObjectName(_fromUtf8("Reco_Outputchooser"))
        self.horizontalLayout_8.addWidget(self.Reco_Outputchooser)
        self.Reco_progressBar = QtGui.QProgressBar(self.groupBox_6)
        self.Reco_progressBar.setGeometry(QtCore.QRect(10, 130, 261, 31))
        self.Reco_progressBar.setProperty("value", 0)
        self.Reco_progressBar.setObjectName(_fromUtf8("Reco_progressBar"))
        self.Reco_Start = QtGui.QPushButton(self.groupBox_6)
        self.Reco_Start.setGeometry(QtCore.QRect(315, 130, 96, 31))
        self.Reco_Start.setObjectName(_fromUtf8("Reco_Start"))
        self.tabWidget.addTab(self.Recognition, _fromUtf8(""))
        self.Conversation = QtGui.QWidget()
        self.Conversation.setObjectName(_fromUtf8("Conversation"))
        self.groupBox_4 = QtGui.QGroupBox(self.Conversation)
        self.groupBox_4.setGeometry(QtCore.QRect(240, 30, 201, 431))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.Conv_Info = QtGui.QTextBrowser(self.groupBox_4)
        self.Conv_Info.setGeometry(QtCore.QRect(0, 30, 193, 351))
        self.Conv_Info.setObjectName(_fromUtf8("Conv_Info"))
        self.Conv_Saveas = QtGui.QPushButton(self.groupBox_4)
        self.Conv_Saveas.setGeometry(QtCore.QRect(0, 390, 96, 31))
        self.Conv_Saveas.setObjectName(_fromUtf8("Conv_Saveas"))
        self.Conv_Clear = QtGui.QPushButton(self.groupBox_4)
        self.Conv_Clear.setGeometry(QtCore.QRect(100, 390, 96, 31))
        self.Conv_Clear.setObjectName(_fromUtf8("Conv_Clear"))
        self.groupBox_5 = QtGui.QGroupBox(self.Conversation)
        self.groupBox_5.setGeometry(QtCore.QRect(70, 180, 141, 211))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.convUsername = QtGui.QLineEdit(self.groupBox_5)
        self.convUsername.setGeometry(QtCore.QRect(0, 170, 131, 33))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.convUsername.sizePolicy().hasHeightForWidth())
        self.convUsername.setSizePolicy(sizePolicy)
        self.convUsername.setObjectName(_fromUtf8("convUsername"))
        self.Conv_Userimage = QtGui.QLabel(self.groupBox_5)
        self.Conv_Userimage.setGeometry(QtCore.QRect(0, 40, 129, 112))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Conv_Userimage.sizePolicy().hasHeightForWidth())
        self.Conv_Userimage.setSizePolicy(sizePolicy)
        self.Conv_Userimage.setText(_fromUtf8(""))
        self.Conv_Userimage.setObjectName(_fromUtf8("Conv_Userimage"))
        self.Conv_Startrecord = QtGui.QPushButton(self.Conversation)
        self.Conv_Startrecord.setGeometry(QtCore.QRect(80, 60, 91, 31))
        self.Conv_Startrecord.setObjectName(_fromUtf8("Conv_Startrecord"))
        self.convTime = QtGui.QLabel(self.Conversation)
        self.convTime.setGeometry(QtCore.QRect(100, 100, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.convTime.setFont(font)
        self.convTime.setObjectName(_fromUtf8("convTime"))
        self.Animation_3 = QtGui.QLabel(self.Conversation)
        self.Animation_3.setGeometry(QtCore.QRect(20, 50, 61, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Animation_3.sizePolicy().hasHeightForWidth())
        self.Animation_3.setSizePolicy(sizePolicy)
        self.Animation_3.setText(_fromUtf8(""))
        self.Animation_3.setObjectName(_fromUtf8("Animation_3"))
        self.tabWidget.addTab(self.Conversation, _fromUtf8(""))
        self.Video = QtGui.QWidget()
        self.Video.setObjectName(_fromUtf8("Video"))
        self.mdiArea = QtGui.QMdiArea(self.Video)
        self.mdiArea.setGeometry(QtCore.QRect(30, 110, 301, 201))
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.horizontalSlider = QtGui.QSlider(self.Video)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 310, 301, 51))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.OpenVideo = QtGui.QPushButton(self.Video)
        self.OpenVideo.setGeometry(QtCore.QRect(30, 60, 96, 31))
        self.OpenVideo.setObjectName(_fromUtf8("OpenVideo"))
        self.label_7 = QtGui.QLabel(self.Video)
        self.label_7.setGeometry(QtCore.QRect(180, 190, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tabWidget.addTab(self.Video, _fromUtf8(""))

        self.retranslateUi(notepad)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.Reco_Verificationcheckbox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.Reco_Verification.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(notepad)

    def retranslateUi(self, notepad):
        notepad.setWindowTitle(_translate("notepad", "Speaker Recognition", None))
        self.groupBox.setTitle(_translate("notepad", "User Info", None))
        self.label_2.setText(_translate("notepad", "Name:", None))
        self.label_3.setText(_translate("notepad", "Age:   ", None))
        self.label_4.setText(_translate("notepad", "Sex:   ", None))
        self.Usersex.setItemText(0, _translate("notepad", "Male", None))
        self.Usersex.setItemText(1, _translate("notepad", "Female", None))
        self.UploadImage.setText(_translate("notepad", "Upload Photo", None))
        self.Userchooser.setItemText(0, _translate("notepad", "(Choose from list)", None))
        self.UpdateInfo.setText(_translate("notepad", "Update Info", None))
        self.ClearInfo.setText(_translate("notepad", "Clear Info", None))
        self.groupBox_2.setTitle(_translate("notepad", "Voice Enrollment", None))
        self.Textreading.setHtml(_translate("notepad", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Youth is not a time of life; it is a state of mind; it is not a matter of rosy cheeks, red lips and supple knees; it is a matter of the will, a quality of the imagination, a vigor of the emotions; it is the freshness of the deep springs of life. </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.label_5.setText(_translate("notepad", "Press \"Record\" and read the following text as clearly as you can.", None))
        self.enroll.setText(_translate("notepad", "Enroll!", None))
        self.startTrain.setText(_translate("notepad", "Train!", None))
        self.dumpBtn.setText(_translate("notepad", "Dump", None))
        self.loadBtn.setText(_translate("notepad", "Load", None))
        self.enrollRecord.setText(_translate("notepad", "Record", None))
        self.stopEnrollRecord.setText(_translate("notepad", "Stop", None))
        self.enrollTime.setText(_translate("notepad", "00:00", None))
        self.enrollFile.setText(_translate("notepad", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Enrollment), _translate("notepad", "Enrollment", None))
        self.groupBox_3.setTitle(_translate("notepad", "Recognition", None))
        self.Reco_Verificationcheckbox.setText(_translate("notepad", "Claim identity:", None))
        self.recoUsername.setText(_translate("notepad", "Unknown", None))
        self.recoTime.setText(_translate("notepad", "00:00", None))
        self.label.setText(_translate("notepad", "* Tick and we will verify your identity", None))
        self.label_10.setText(_translate("notepad", "Here is a little animation", None))
        self.newReco.setText(_translate("notepad", "New Task", None))
        self.recoRecord.setText(_translate("notepad", "Record", None))
        self.stopRecoRecord.setText(_translate("notepad", "Stop", None))
        self.recoFile.setText(_translate("notepad", "...", None))
        self.groupBox_6.setTitle(_translate("notepad", "Multiple tasks from files", None))
        self.label_8.setText(_translate("notepad", "Input folder:   ", None))
        self.Reco_Inputchooser.setText(_translate("notepad", "...", None))
        self.label_9.setText(_translate("notepad", "Output folder:", None))
        self.Reco_Outputchooser.setText(_translate("notepad", "...", None))
        self.Reco_Start.setText(_translate("notepad", "Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Recognition), _translate("notepad", "Recognition", None))
        self.groupBox_4.setTitle(_translate("notepad", "Conversation Info", None))
        self.Conv_Saveas.setText(_translate("notepad", "Save as..", None))
        self.Conv_Clear.setText(_translate("notepad", "Clear", None))
        self.groupBox_5.setTitle(_translate("notepad", "Current Speaker", None))
        self.Conv_Startrecord.setText(_translate("notepad", "Record", None))
        self.convTime.setText(_translate("notepad", "00:00", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Conversation), _translate("notepad", "Conversation Mode", None))
        self.OpenVideo.setText(_translate("notepad", "Open...", None))
        self.label_7.setText(_translate("notepad", "This page is under construction", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Video), _translate("notepad", "Video Mode", None))

